<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN">
<html><body>
<p>I get the following error when I try to run the following python code</p>
<div>import mpi4py.MPI as MPI</div>
<div>comm = &nbsp;MPI.COMM_WORLD</div>
<div>MPI.File.Open(comm,"some.file")</div>
<div>&nbsp;</div>
<div>$ mpirun -np 1 python test_mpi.py<br />Traceback (most recent call last):<br />&nbsp; File "test_mpi.py", line 3, in &lt;module&gt;<br />&nbsp;&nbsp;&nbsp; MPI.File.Open(comm," h5ex_d_alloc.h5")<br />&nbsp; File "File.pyx", line 67, in mpi4py.MPI.File.Open (src/mpi4py.MPI.c:89639)<br />mpi4py.MPI.Exception: MPI_ERR_OTHER: known error not in list<br />--------------------------------------------------------------------------<br />mpirun noticed that the job aborted, but has no info as to the process<br />that caused that situation.<br />--------------------------------------------------------------------------</div>
<div>&nbsp;</div>
<div>My mpirun version is (Open MPI) 1.6.2. I installed openmpi using the dorsal script (https://github.com/FEniCS/dorsal) for Redhat Enterprise 6 (OS I am using, release 6.5) . It configured the build as following :</div>
<div>&nbsp;</div>
<div>./configure --enable-mpi-thread-multiple --enable-opal-multi-threads --with-threads=posix --disable-mpi-profile<br /><br /></div>
<div>I need emphasize that I do not have root acces on the system I am running my application.</div>
<div>&nbsp;</div>
<div>Imran</div>
<div>&nbsp;</div>
<div>&nbsp;</div>
</body></html>

